# -*- coding: utf-8 -*-
# Copyright 2023 Ant Group CO., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

# ATTENTION!
# This file is generated by Schema automatically, it will be refreshed after schema has been committed
# PLEASE DO NOT MODIFY THIS FILE!!!
#

from knext.common.schema_helper import SPGTypeHelper, PropertyHelper, RelationHelper


class TEST:
    class CenterEvent(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        subject = PropertyHelper("subject")
        standardProperty = PropertyHelper("standardProperty")
        conceptProperty = PropertyHelper("conceptProperty")
        eventTime = PropertyHelper("eventTime")
        basicTextProperty = PropertyHelper("basicTextProperty")
        basicIntegerProperty = PropertyHelper("basicIntegerProperty")
        basicFloatProperty = PropertyHelper("basicFloatProperty")

        eventRelation = RelationHelper("eventRelation")

    class Concept1(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        alias = PropertyHelper("alias")
        stdId = PropertyHelper("stdId")

        leadTo = RelationHelper("leadTo")

    class Concept2(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        alias = PropertyHelper("alias")
        stdId = PropertyHelper("stdId")

    class Concept3(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")
        stdId = PropertyHelper("stdId")
        alias = PropertyHelper("alias")

    class Entity1(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")

        entityRelation = RelationHelper("entityRelation")
        predictRelation = RelationHelper("predictRelation")

    class Entity2(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")

    class Entity3(SPGTypeHelper):
        description = PropertyHelper("description")
        id = PropertyHelper("id")
        name = PropertyHelper("name")

    CenterEvent = CenterEvent("TEST.CenterEvent")
    Concept1 = Concept1("TEST.Concept1")
    Concept2 = Concept2("TEST.Concept2")
    Concept3 = Concept3("TEST.Concept3")
    Entity1 = Entity1("TEST.Entity1")
    Entity2 = Entity2("TEST.Entity2")
    Entity3 = Entity3("TEST.Entity3")

    pass
